### ISSUE TITLE
[edit] Replace CEC with Chaibasa Engineering College 

### ISSUE THREAD

**Issue by 1Shubham7** [NageshMandal/Engineering-Notes-Website#1002]
![cec](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/f1387814-192c-468f-a13e-e4e90fe0386c)

Here the CEC can be replaced with Chaibasa Engineering College because not all people know the full form of CEC

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by ShrutiSingh04503** [comment]
Hey I would like to work on this issue
