### ISSUE TITLE
Contact button on nav bar

### ISSUE THREAD

**Issue by kasturimandlik** [NageshMandal/Engineering-Notes-Website#103]
Hello, the contact button on the navbar is not working.
I would like to make this button working and contact information on the page.
Please assign me this issue.
I would like to work on this issue under GSSOC'23.

**Comment by RahulRana701** [comment]
I would like to work on this issue @NageshMandal please assign it to me........

**Comment by shramanpaul** [comment]
I would like to work on this issue under GSSOC'23 ,  @NageshMandal

**Comment by AnuragK2** [comment]
I would like to work on this issue.

**Comment by PatilHarshh** [comment]
I would love to work upon it @NageshMandal

**Comment by ruchagosavi** [comment]
I would like to work on it please assign me!! @NageshMandal

**Comment by kasturimandlik** [comment]
@NageshMandal Thank you for assigning me this issue. Can you please tell me about any specific requirement you want ?

**Comment by Divya7201** [comment]
I would like to work on this issue under GSSOC'23.

**Comment by pjyoti121** [comment]
I would like to work on this issue under GSSOC'23.
