### ISSUE TITLE
youtube button misaligned

### ISSUE THREAD

**Issue by sumitkr2000** [NageshMandal/Engineering-Notes-Website#1105]
Hey, @NageshMandal The YouTube button in the footer is misaligned. Please assign me this issue. Thank you!

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/100675296/c639a0df-3e72-4057-8f36-2daf084996e7)

**Comment by Neha626177** [comment]
The YouTube button in the footer is misaligned. Please assign me this issue.I would like solve this issue
