### ISSUE TITLE
Major improvement in subjects page

### ISSUE THREAD

**Issue by jessicacb12** [NageshMandal/Engineering-Notes-Website#114]
@NageshMandal Greetings I'm Jessica from GSSOC. I notice when I opened any of the subjects page, I have to hover to check whether the module pdf is actually available 

So here are my suggestions (I'm open to suggestion):

- [ ] Add explanation for the abbreviation. E.g: what is the actual name of D.M.S, T.O.C, etc
- [x] Use card to show modules. That way we can provide more information about the module. E.g: title, description
- [ ] Based on previous points, I think it's better to show the sections list vertically instead of horizontally. Maybe we can wrap them as collapsible which will show the modules when opened
- [x] Integrate pdf viewer to the page so that the user doesn't need to be redirected to new page to open the pdf. The pdf viewer should enable them to also download the pdf

Please let me know your thoughts. If you're agree, I'll separate above items to give opportunities to others to also help with this.

**Comment by abcxyz31** [comment]
yeah we can work on this ..
