### ISSUE TITLE
UI issue in your navbar:  Misalignment of Sun Icon in Navbar

### ISSUE THREAD

**Issue by rishabh-nahar** [NageshMandal/Engineering-Notes-Website#1146]
The sun icon in the navbar of the repository's UI is not aligned properly, which affects the overall visual harmony and consistency of the design. The misalignment could be attributed to CSS positioning, alignment settings, or an issue with the icon's implementation.

Expected Behavior:
The sun icon should be aligned in a visually pleasing and consistent manner within the navbar. It should maintain the same alignment and positioning as other navbar elements, ensuring a cohesive and polished appearance.

**Comment by Ganaik2004** [comment]
@rishabh-nahar I want to work on this issue please assign it to me

**Comment by SyedImtiyaz-1** [comment]
Can you please assign me this issue.

**Comment by SyedImtiyaz-1** [comment]
can you please assign me this project ?

**Comment by SyedImtiyaz-1** [comment]
can you please assign me this issue ?

**Comment by SyedImtiyaz-1** [comment]
can you please assign me this issue ?
