### ISSUE TITLE
Improving Newsletter form

### ISSUE THREAD

**Issue by Yash7426** [NageshMandal/Engineering-Notes-Website#118]
Bug - Submitting incorrect email id shows black screen
![eeee](https://github.com/NageshMandal/Engineering-Notes-Website/assets/119874901/1f58da8d-698d-4da9-a5fc-3daf8b71e792)
I would like to work on the issue, please assign it to me

**Comment by Hritik1503** [comment]
I would like to work on this issue under GSSoC'23. Please assign me this issue.
