### ISSUE TITLE
SEO of the Complete Website

### ISSUE THREAD

**Issue by Girishnikam** [NageshMandal/Engineering-Notes-Website#120]
[GSSoC 2023] SEO-friendly website can increase website credibility, improve user experience and get more users on our website. For making the website SEO friendly I'll like to implement following things

- Optimize the title tags and meta descriptions
- Using keywords in the website content (will perform proper research for keywords across all the search engines)
- Include keyword-rich anchor text in links
- Compressing the media (images, illustrations) to make sure website loads faster
- Clean up and organize the complete code 
- (Optional) Implement various Google tools like Google Analytics, Google Search Console to see how site is performing in Google search results

Find the attachment of example, how optimization will help to boost performance of the website

![use of title and meta description optimisation](https://github.com/NageshMandal/Engineering-Notes-Website/assets/84145346/e0854bfa-1670-465f-9674-35ea06ccccbb)

**Comment by Girishnikam** [comment]
Thank you!

**Comment by NageshMandal** [comment]
@Girishnikam Any Update

**Comment by Girishnikam** [comment]
Yes, I'm working on it, due to my exams and more changes to be made, caused me delay. Sorry for the inconveniences. Shall create a pull request soon.

**Comment by Girishnikam** [comment]
Pull request merged. Closing the issue with status completed
