### ISSUE TITLE
Dark mode getting off when page is refresh

### ISSUE THREAD

**Issue by NageshMandal** [NageshMandal/Engineering-Notes-Website#14]
when we refresh the page the dark mode getting off or when we enter branch page it getting of could any one can solve it

**Comment by MufaddalHakim** [comment]
I would like to work on this. Please assign.

**Comment by rahul-s-bhatt** [comment]
Hi Nagesh, we should be able to fix this by saving the state to localStorage, please assign it to me, I shall fix this bug.

**Comment by MufaddalHakim** [comment]
I'm already working on it, please let me take this

**Comment by MufaddalHakim** [comment]
Fixed the issue, please review and merge pr

**Comment by NageshMandal** [comment]
@MufaddalHakim it is not working properly
it need some changes
