### ISSUE TITLE
Branches Section

### ISSUE THREAD

**Issue by shruti8302** [NageshMandal/Engineering-Notes-Website#152]
Hey @NageshMandal,
As a part of GSSOC'23, I would like to improve the branches in CEC section by improving the height and width as well as shadow around it. I would also like to add transition effect on hovering. I also want to change the font size of the heading - Branches in CEC. Kindly assign me this issue.

**Comment by Hritik1503** [comment]
I would like to work on this issue under GSSoC'23. Please assign me this issue.
