### ISSUE TITLE
I want to create Gallay Section

### ISSUE THREAD

**Issue by Durgesh4993** [NageshMandal/Engineering-Notes-Website#163]
When i'll clicked on gallary section there are no image showing can i create the page

**Comment by Durgesh4993** [comment]
https://github.com/NageshMandal/Engineering-Notes-Website/assets/98798977/10a27ee7-ae12-443c-b518-a95098135a3d

**Comment by Durgesh4993** [comment]
As you their are no images are loaded

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
