### ISSUE TITLE
Add Complete Handwritten Note's in Format for Microprocessor(B.Tech.)

### ISSUE THREAD

**Issue by Sudhanshu-Sharma-22** [NageshMandal/Engineering-Notes-Website#167]
I want to add all my handwritten note's which are completely in format and completely visible/readable in this repo.

**Comment by Sudhanshu-Sharma-22** [comment]
Hey @NageshMandal , i have prepared the notes where should i push them in repo?

**Comment by ankitbose002** [comment]
I want to add all my handwritten note's which are completely in format and completely visible/readable in this repo.

**Comment by Sudhanshu-Sharma-22** [comment]
@ankitbose002 Sure you can add it but i am making the html page right now after that you can push your notes in that repo/page.🙃.....

**Comment by ankitbose002** [comment]
when you well assign me to contribute.

**Comment by hustler0109** [comment]
Having a strong passion for Microprocessor architecture and B.Tech. studies, I believe I can make a meaningful contribution by creating and adding comprehensive handwritten notes in a user-friendly format. These notes would serve as valuable resources for students studying Microprocessor in the B.Tech. program, helping them grasp the concepts more effectively. As a diligent contributor, I am committed to providing high-quality content and ensuring that the notes are well-structured, accurate, and easy to understand. I will take care to adhere to any specific formatting guidelines provided by the repository and maintain consistency with the existing content.

I have experience with similar contributions in the past and am comfortable working with GitHub repositories, version control, and collaborative workflows.
Please assign this issue to me under gssoc'23
