### ISSUE TITLE
Text not visible in Dark Mode

### ISSUE THREAD

**Issue by Sh4dab** [NageshMandal/Engineering-Notes-Website#173]
Hello, I am a GSSOC'23 Contributor and want to contribute to this project.

The text on the front page is not clearly visible while switching to the dark mode, its color is not changing while switching to dark mode.

![c2](https://github.com/NageshMandal/Engineering-Notes-Website/assets/97034961/15d4aac0-15b1-4962-a2f1-c85b3c8b058a)

can you please assign me this issue under GSsoc'23

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by kumarkshitij171** [comment]
is issue still there
if yes then assign it to me.

**Comment by Sh4dab** [comment]
someone solved already :(
