### ISSUE TITLE
Fix Dark Mode Button Issue

### ISSUE THREAD

**Issue by Geetanjaligupta123** [NageshMandal/Engineering-Notes-Website#18]
Can you please assign this issue to me :)

**Comment by NageshMandal** [comment]
![05 10 2022_11 44 28_REC](https://user-images.githubusercontent.com/106006006/193995408-e6b16d0f-0e05-44ce-898b-745371c05079.png)
Could you please fix the issue

**Comment by Geetanjaligupta123** [comment]
sure

**Comment by Geetanjaligupta123** [comment]
Can you please tell me what I have to fix??

**Comment by NageshMandal** [comment]
https://user-images.githubusercontent.com/106006006/194013513-c72302e4-4455-4440-9d8a-59b6967f0b4b.mp4

**Comment by NageshMandal** [comment]
it should look like this when we open the web site

**Comment by Geetanjaligupta123** [comment]
Alright

**Comment by Geetanjaligupta123** [comment]
ok
