### ISSUE TITLE
Navbar buttons are not visible for small screen 

### ISSUE THREAD

**Issue by varsha-saini02** [NageshMandal/Engineering-Notes-Website#189]
Hello,
The navbar buttons are not visible in small screen. I can fix it please assign me this issue under GSSOC'23.

Thank you.

**Comment by Adityakumarsinghstm** [comment]
please assign this issue to me under GSSOC'23

**Comment by Avinash-NCEIAN** [comment]
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/86868626/b7dab725-4c31-44a5-91cf-c30cf8cfceb9)

I want to work on this Project. Plzz assign it to me

**Comment by varsha-saini02** [comment]
Thank you for assigning. i'm working on it.
