### ISSUE TITLE
 Site is not responsive below 360px viewport width and navbar become unresponsive below 865px  viewport width.

### ISSUE THREAD

**Issue by gauravsingh1281** [NageshMandal/Engineering-Notes-Website#192]

**Comment by gauravsingh1281** [comment]
<img width="581" alt="Screenshot 2023-05-21 225657" src="https://github.com/NageshMandal/Engineering-Notes-Website/assets/85905403/473f0cc4-35d3-4e47-a288-a3493b403b5a">

 The site is not responsive below 354px viewport width ⬆️.

**Comment by gauravsingh1281** [comment]
<img width="578" alt="Screenshot 2023-05-21 225927" src="https://github.com/NageshMandal/Engineering-Notes-Website/assets/85905403/e0c26532-eed5-40ae-b0a9-e4b9cc8655e6">

 No navbar in mobile view ⬆️.

**Comment by gauravsingh1281** [comment]
<img width="578" alt="Screenshot 2023-05-21 230357" src="https://github.com/NageshMandal/Engineering-Notes-Website/assets/85905403/eb88633f-1aaa-45d7-a345-14c6404b1328">

Navbar becomes unresponsive below 750px viewport width ⬆️.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by Avinash-NCEIAN** [comment]
![Screenshot (629)](https://github.com/NageshMandal/Engineering-Notes-Website/assets/86868626/23b9572c-1e69-41be-8056-e9c83f5c5852)
![Screenshot (629)](https://github.com/NageshMandal/Engineering-Notes-Website/assets/86868626/7ecea82e-15f8-4a89-ad7d-651c782ac9d6)

**Comment by gauravsingh1281** [comment]
Please assign this project to me because I have raised the issue first and i want to work on it.

**Comment by gauravsingh1281** [comment]
Thank you for assigning this task to me😇.

**Comment by gauravsingh1281** [comment]
#231

**Comment by gauravsingh1281** [comment]
#231 Issue No. #192 - Navbar responsiveness issue below 865px viewport width and site responsiveness issue below 360px viewport width fixed.

**Comment by gauravsingh1281** [comment]
Thank you for assigning this task to me😇.

**Comment by gauravsingh1281** [comment]
<img width="572" alt="Screenshot 2023-05-22 185336" src="https://github.com/NageshMandal/Engineering-Notes-Website/assets/85905403/ded282b3-ac4d-41b1-9f7f-5a513b6fb0d8">

Site responsiveness issue below 360px viewport width fixed ⬆️.

**Comment by gauravsingh1281** [comment]
#231 Issue No. #192 - Navbar responsiveness issue below 865px viewport width and site responsiveness issue below 360px viewport width is fixed.
