### ISSUE TITLE
Link the syllabus of each semester to the college website and changes in navbar under departments 

### ISSUE THREAD

**Issue by PoulavBhowmick03** [NageshMandal/Engineering-Notes-Website#197]
I would like to add the syllabus of each Sem under every department, since most of them redirect to the college Website
I would also like to change the navbar for the departments
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/133862694/33403ae8-05a9-41d5-aed9-4bc71ac69ace)
Also, add the functionality of opening to a new tab on clicking any linked element
Please assign this to me @NageshMandal

**Comment by PoulavBhowmick03** [comment]
Also, the contact button on the home page doesn't work. If I am allowed, I can link that too. @NageshMandal

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by Nishka30** [comment]
I want to work on this issue. Can u please assign this issue to me?

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by PoulavBhowmick03** [comment]
It's been 5 days @NageshMandal . Can you please assign this to me?

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by PoulavBhowmick03** [comment]
@NageshMandal Please assign this issue. It's been 3 weeks since I made this
