### ISSUE TITLE
CSE NOTES

### ISSUE THREAD

**Issue by Killer2OP** [NageshMandal/Engineering-Notes-Website#210]
Adding the incomplete notes in 4th SEM and also add the notes of 5th , 6th ,7th and 8th SEM 
Assign me this under GSSoC''23.

**Comment by 91aman91** [comment]
i wanna work on this project

**Comment by stuti187** [comment]
i am willing to work on this issue

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.

**Comment by Lavesh12** [comment]
please assign me this issue
