### ISSUE TITLE
Logo for the website

### ISSUE THREAD

**Issue by Killer2OP** [NageshMandal/Engineering-Notes-Website#213]
### Suggestion
As mentioned in Issue #113 
This website is not looking as engineering notes website.

**PROBLEM**
As the website has no logo or a design which indicates it as a Engineering notes website. We can create a logo which will help the website look more attractive.
If so I can help in making that logo for the website. 

If you liked what I proposed assign me this issue under GSSoC'23

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.

**Comment by Hritik1503** [comment]
I would like to work on this issue under GSSoC'23. Please assign me this issue.
