### ISSUE TITLE
Footer `Number & Mail` is not Clickable

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [NageshMandal/Engineering-Notes-Website#277]
Hello @NageshMandal,

## Details - 
Number and Mail on each page is not `Clickable`

## Screenshot -
![Screenshot from 2023-05-23 17-49-14](https://github.com/NageshMandal/Engineering-Notes-Website/assets/121503426/06a6c429-a351-4f46-80bd-d5e2e2584ba9)

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by SyedImtiyaz-1** [comment]
I have already raised a PR
