### ISSUE TITLE
Dark mode not working in many pages of the website.

### ISSUE THREAD

**Issue by 1Shubham7** [NageshMandal/Engineering-Notes-Website#285]
Dark mode is not working in any webpage accept the home page, but it still shows the option of dark mode, but nothing happens upon clicking on the button.

![isuue](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/b04d186f-ad5b-4199-9ec9-0c31924f39eb)

**Comment by 1Shubham7** [comment]
@NageshMandal The dark mode has started working, did you merge any such code?

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by 1Shubham7** [comment]
@NageshMandal This issue has been resolved, shall I close the issue?

**Comment by 1Shubham7** [comment]
Closing it after talking to @NageshMandal
