### ISSUE TITLE
Creating Navbar for Mobile !!

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [NageshMandal/Engineering-Notes-Website#294]
Hye
I want to Create a Navbar for Mobile Phones
Please Assign me this issue as a GSSOC'23 Contributor.

I can see No Navbar is there for Mobile
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/83361657/8685a8e9-1a92-4e26-a8b2-b5b08fcb9e51)

**Comment by Gurmeet-Singh657** [comment]
@NageshMandal As per the rule, Issues will be assigned in the form of FCFS, but you assigned this issue to someone even when I opened this request earlier . Why ?

**Comment by Lavesh12** [comment]
please assign me this issue
