### ISSUE TITLE
Navigation bar disappears in Mobile mode(not responsive)

### ISSUE THREAD

**Issue by kavya-agrwl** [NageshMandal/Engineering-Notes-Website#295]
the NAVIGATION bar disappears when switched to mobile mode, hence it is not responsive.I can make it convert to hamburger menu while it is opened in the mobile.
I have previously made hamburger menu by using Javascript, hence please assign this task to me under GSSOC'23.
A picture of this issue is attached here.
![Screenshot (32)](https://github.com/NageshMandal/Engineering-Notes-Website/assets/90094340/78c6d7c4-27f4-4ef6-bee7-67e45bd3faa4)

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
