### ISSUE TITLE
Make A On/Off Button For Voice Assistant 

### ISSUE THREAD

**Issue by NageshMandal** [NageshMandal/Engineering-Notes-Website#30]
![06 10 2022_22 53 00_REC](https://user-images.githubusercontent.com/106006006/194382606-e1820304-42dd-464d-9d6b-21e044c17733.png)
**set this button to on voice assistant**
![06 10 2022_22 55 41_REC](https://user-images.githubusercontent.com/106006006/194382727-675a1b1c-32f0-4ba4-818c-69933c2cbbcf.png)
**Currently when we open the website the voice assistant get automated**
**-------------------------------------------**
**voice assistant Commands**
(1) open computer science branch
(2) open Electronics branch

use this commands to test your changes

**Comment by NageshMandal** [comment]
Voice Assistant file --- app.js

**Comment by nithin-gith** [comment]
I like to work on this feature please assign me this

**Comment by nithin-gith** [comment]
Can you please close this issue.
