### ISSUE TITLE
Better color gradient for light mode!

### ISSUE THREAD

**Issue by Shr-reny** [NageshMandal/Engineering-Notes-Website#308]
We can change the color gradient from pink to any other light color compatible with switching from light to dark mode.

**Comment by dheeraj1129** [comment]
hello @Shr-reny I am interested  in this project task please assign this task.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
