### ISSUE TITLE
Fix Text in README

### ISSUE THREAD

**Issue by Sriparno08** [NageshMandal/Engineering-Notes-Website#323]
According to the table of contents, the following section:

> ## HTML, CSS, JS, BOOTSTRAP, API
>
> List the technologies and programming languages used in your project.

should be changed to:

> ## Technologies
>
> HTML, CSS, JS, BOOTSTRAP, API

**Comment by Khushal747** [comment]
I would like to contribute in this as my first gssoc contribution please assign me this issue

**Comment by Lavesh12** [comment]
please assign me this issue
