### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Laxmankohar** [NageshMandal/Engineering-Notes-Website#33]
Since there is no favicon currently we can put one there.
This issue is opened under Hacktoberfest.

**Comment by Laxmankohar** [comment]
@NageshMandal I would like to work on this issue.

**Comment by Laxmankohar** [comment]
@NageshMandal  i am going to use this. is it ok?

![school](https://user-images.githubusercontent.com/73365025/194816316-388204d4-a7ff-439d-8161-281093da4e39.png)

**Comment by Laxmankohar** [comment]
@NageshMandal  is it ok ?
![Screenshot (139)](https://user-images.githubusercontent.com/73365025/194826692-e7fe0744-b4f4-46f6-b315-996d1abe18f7.png)

**Comment by Laxmankohar** [comment]
@NageshMandal Check it once after that i will make a pull request.

![image](https://user-images.githubusercontent.com/73365025/194829865-160c1832-5bf5-4dc2-9e37-ab8e4cf524ec.png)

**Comment by NageshMandal** [comment]
yes 😍
