### ISSUE TITLE
To set Google Map link of Chaibasa Engineering College in Footer Section

### ISSUE THREAD

**Issue by ombhojane** [NageshMandal/Engineering-Notes-Website#343]
Hey, I've tried to find the location of Chaibasa Engineering College, but when I clicked on the text, it does not redirected me to desired location.
This is happened because, there is not link set for location of Chaibasa Engineering College in Footer section yet.
I can fix this issue, results user can navigate to Chaibasa Engineering College's Google Map Location!
Can you please assign this issue to me..
GSSOC 2023 :)

**Comment by ombhojane** [comment]
Hey, @NageshMandal ,
Issue is not resolved yet, can you please assign this issue to me

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by ombhojane** [comment]
Issue Resolved
