### ISSUE TITLE
Add the data of the other branches also

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [NageshMandal/Engineering-Notes-Website#359]
I kindly request the addition of a dedicated section for textile technology in order to provide comprehensive and semester-wise aligned study materials. 
As the availability of such resources online is limited, this addition would greatly benefit students pursuing textile technology by facilitating easy access to the required educational materials.

**Comment by Avdhesh-Varshney** [comment]
Please assign this task to me, please !

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@NageshMandal please assign this task to me to create pr under GSSoC'23 program
