### ISSUE TITLE
Add notes in notes in SEM 2, 3, 4, 5, 6, 7, 8

### ISSUE THREAD

**Issue by deepeshgupta3257** [NageshMandal/Engineering-Notes-Website#380]
Add notes to these semester as only 1 sem notes are linked. 
please assign me this issue under gssoc'23 I can link the notes of the other sem.
I want to work on this issue please assign me this issue under gssoc'23

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by RazzaqShikalgar** [comment]
i do have more content for all sem's can i work on this issue
