### ISSUE TITLE
copy right reserved 

### ISSUE THREAD

**Issue by Sushilverma002** [NageshMandal/Engineering-Notes-Website#386]
in this issue i want to add copy right footer in last of website so that it will protect from copy right.
it will look like this:
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/114687502/f17063ad-a3e4-4f1b-8c87-0d016adab2a3)

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor
