### ISSUE TITLE
nav bar response 

### ISSUE THREAD

**Issue by Sushilverma002** [NageshMandal/Engineering-Notes-Website#387]
when ever user click on contact button it will re-directed to the last section of the page that what the footer contain the information.
click on contact:
![Screenshot 2023-05-27 170444](https://github.com/NageshMandal/Engineering-Notes-Website/assets/114687502/e018daec-4d62-4169-86f2-4cffcd72ab72)

after that redirected to this contact page:
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/114687502/416faf77-a8f2-4ad8-803e-9914a005cbdc)

**Comment by Sushilverma002** [comment]
> when ever user click on contact button it will re-directed to the last section of the page that what the footer contain the information. click on contact: 
![Screenshot 2023-05-27 170444](https://github.com/NageshMandal/Engineering-Notes-Website/assets/114687502/52184083-1e0e-4541-a1a6-0efa08860d5c)
after that redirected to this contact page: ![image](https://user-images.githubusercontent.com/114687502/241386474-416faf77-a8f2-4ad8-803e-9914a005cbdc.png)

**Comment by muskanmandloi** [comment]
Please assign this issue to me

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by Sushilverma002** [comment]
@NageshMandal please check this issue.
i added the pull request
