### ISSUE TITLE
Navbar is not completely responsive

### ISSUE THREAD

**Issue by PVBharadwaj** [NageshMandal/Engineering-Notes-Website#397]
NavBar keys are not visible in mobile view. I would like to fix the issue. Please assign it to me under GSSOC'23 @NageshMandal

**Comment by vishnubansal001** [comment]
I was assigned this task and i have completed that the only thing remaining is that of merging the pull request

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by PVBharadwaj** [comment]
> I was assigned this task and i have completed that the only thing remaining is that of merging the pull request

Ok
I didn't noticed that this issue was raised earlier. I will close this issue.
