### ISSUE TITLE
[FEAT]: IMPROVE PAGE LOAD TIME BY OPTIMIZING IMAGE ASSETS

### ISSUE THREAD

**Issue by 0xabdulkhalid** [NageshMandal/Engineering-Notes-Website#399]
### Description

- The site uses `jpg`, `png` & `svg` types of images, but the `jpg` images are always tend to be more larger in size so that the page takes more bandwith to load it
- It severly affects page load time, because it may uncomfortable for the people who having a moderate internet connection
- My plan is to convert all those `jpg` images to `webp` to minimize the page load time and bandwith
- Currently the `png`, & `svg` are not going to converted only the `jpg` files are to be focused

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

### PS
- I'm a participant of `GSSoC2023` so assign this issue to me under `GSSoC2023`
- Happy to contribute!

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by 0xabdulkhalid** [comment]
Brother @Harshvardhan-Dubey-Github, this issue is already assigned for me.

So kindly work on another issue.

Regards

**Comment by Harshvardhan-Dubey-Github** [comment]
> Brother @Harshvardhan-Dubey-Github, this issue is already assigned for me and i'm currently working to resolve it!
> 
> You need to create your own, so kindly work on another issue.
> 
> Regards

okay bro no problem

**Comment by 0xabdulkhalid** [comment]
@NageshMandal, the PR has been opened kindly review the changes and merge it. So i can create another issue to work on it
