### ISSUE TITLE
Cards of Branches in CEC could be more attractive and better arrangement.

### ISSUE THREAD

**Issue by mahak-dev** [NageshMandal/Engineering-Notes-Website#413]
I wanted to share a suggestion regarding the branch cards on your website. While navigating through the site, I noticed that the branch cards could benefit from a more appealing design and improved arrangement. By enhancing the visual appeal and optimizing their organization, I can create a more user-friendly experience for visitors.

**Comment by Lavesh12** [comment]
please assign me this issue

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by mahak-dev** [comment]
I am already working on it.

**Comment by 91aman91** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by mahak-dev** [comment]
Issues has been resolved.
