### ISSUE TITLE
Give Proper Spacing to Hero Section [GSSOC'23]

### ISSUE THREAD

**Issue by kartikayasija** [NageshMandal/Engineering-Notes-Website#43]
The hero section is looking very messy, it should have proper Padding and spacing.

<img width="960" alt="image" src="https://github.com/NageshMandal/Engineering-Notes-Website/assets/115306535/10dbb810-7c2b-4b0a-9ae4-f616eafadc82">

Assign me this issue under GSSOC'23.

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by NehaShrama** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.
