### ISSUE TITLE
Fix Table of Contents

### ISSUE THREAD

**Issue by Sriparno08** [NageshMandal/Engineering-Notes-Website#479]
Table of Contents is not formatted correctly.

![Screenshot 2023-06-01 111245](https://github.com/NageshMandal/Engineering-Notes-Website/assets/89148144/69d0e965-2155-46d7-a6fd-35c2ca38e909)

I would like to contribute the formatting as part of GSSoC'23.

**Comment by steffigeorge** [comment]
I can resolve this issue! Please assign me this
