### ISSUE TITLE
Updating all the latest contributors in README

### ISSUE THREAD

**Issue by linga66** [NageshMandal/Engineering-Notes-Website#515]
Hi @NageshMandal 
I would like to improvise the readme.md file up-to a great extent.

Also, describe the documentation you want to add. ✍️
We can display all the active and latest contributors on README.md file

Please assign me this issue @NageshMandal .
I believe I can Do this.

**Comment by Anjali2312-Thombare** [comment]
hey @linga66  I will update the readme file. Can you please assign me this issue?
