### ISSUE TITLE
Creating an about us page that can be linked to about us on the footer [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [NageshMandal/Engineering-Notes-Website#519]
The Footer of the website has an about us page but it takes you back to the homepage. I can create an about us page tor the link to make the website more professional.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by aditi-chaurasia** [comment]
Please assign this task to me for making changes.

**Comment by 1Shubham7** [comment]
@aditi-chaurasia This issue has been resolved. Thank you for your concern.

**Comment by 1Shubham7** [comment]
@NageshMandal Bhaiya Please review it fast I have One more PR to close and Issue.
