### ISSUE TITLE
[GssoC '23] Add Syllabus Section for different colleges and Sorting Feature with YouTube Lecture Links

### ISSUE THREAD

**Issue by exploring-solver** [NageshMandal/Engineering-Notes-Website#560]
Description: This issue involves adding a new section to the engineering notes website that displays syllabus information from various colleges. The section will enable students to easily access and compare syllabi across different institutions. Additionally, a sorting feature will be implemented, allowing users to filter syllabi by college and subject for efficient browsing. Furthermore, integrating lecture links from YouTube will provide students with direct access to relevant video content, enhancing their learning experience. This enhancement will empower students by providing comprehensive syllabus resources and convenient sorting capabilities, fostering a more productive and streamlined studying environment.
I look forward to work on this issue please assign this to me

**Comment by mandliyarajendra11** [comment]
@exploring-solver are you still working on this issue 
if not then @NageshMandal  please assign me

**Comment by exploring-solver** [comment]
> @exploring-solver are you still working on this issue 
> if not then @NageshMandal  please assign me 

@mandliyarajendra11 Yes i am still working on this issue ☺
