### ISSUE TITLE
contact form bug.

### ISSUE THREAD

**Issue by Sushilverma002** [NageshMandal/Engineering-Notes-Website#572]
the nav bar must be fixed at the top so that if user wants to switch the tab he/she can.

https://github.com/NageshMandal/Engineering-Notes-Website/assets/114687502/3d6d7c39-612e-496e-96d8-2370c293a788

**Comment by priyanka0815** [comment]
Please provide me this issue under GSSoC'23, I can fix this and will make a PR soon.
