### ISSUE TITLE
Hover effect on mic and buttons is very poor. Improving it [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [NageshMandal/Engineering-Notes-Website#586]
This is how the mic icon looks upon hovering:
![mix](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/8201dbe7-16c3-46f0-8732-9129a1df4e38)

It is not looking very interesting, I can improve this.
Please assign me this issue.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by muskanmandloi** [comment]
please assign it to me.

**Comment by 1Shubham7** [comment]
@muskanmandloi I think I can do it on my own. Thank you for your concern.
