### ISSUE TITLE
Bug: No dark mode available in contact us page. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [NageshMandal/Engineering-Notes-Website#587]
There is no option of dark mode in the contact us page. 
![nodarkmode](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/bdcd5cb2-3147-4c9c-b734-4c07fde9d44f)

I can add dark mode button and a dark mode.
Please assign me this issue.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by kaashikaagrawal** [comment]
Hi i have dark mode implementation code ready. Can you assign this issue to me?

**Comment by 1Shubham7** [comment]
Thank you @NageshMandal bhaiya. I will surely not disappoint you.
