### ISSUE TITLE
Search bar text is not visible

### ISSUE THREAD

**Issue by SubhamB2003** [NageshMandal/Engineering-Notes-Website#634]
@NageshMandal Hey, can I work on it?
The search bar text is not visible properly in light mode

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/94003231/528ac20a-3330-4fb3-9ae8-07abb6ee4cf8)

I want to fix this issue Under GSSOC'23. Please assign it to me.

**Comment by tusharban42** [comment]
I want to fix this issue Under GSSOC'23. Please assign it to me.

**Comment by Atulsingh30** [comment]
@NageshMandal Please assign this issue to me
