### ISSUE TITLE
No validation in contact us form inputs

### ISSUE THREAD

**Issue by Avinash905** [NageshMandal/Engineering-Notes-Website#675]
### Description:

There is no validation applied to the inputs of contact us form.

![Screenshot (498)](https://github.com/NageshMandal/Engineering-Notes-Website/assets/56786344/1153fd4f-9c75-4b33-bc2e-ff4cdb7f7faf)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Lavesh12** [comment]
please assign me this issue.
