### ISSUE TITLE
Improving the Positioning of the 'Explore Now' button in the Home Page.

### ISSUE THREAD

**Issue by saqlain2204** [NageshMandal/Engineering-Notes-Website#78]
Improper placement of the Explore Now button resulted in a suboptimal User Interface experience, detracting from the overall usability and appeal of the application.

**Comment by premsaivarmachekuri** [comment]
@NageshMandal. I wanted to bring your attention to an issue regarding the positioning of the 'Explore Now' button on the Home Page. Currently, its placement is suboptimal and negatively impacts the User Interface (UI) experience, detracting from the overall usability and appeal of the application.

To enhance the UI and provide a more intuitive user experience, I suggest improving the positioning of the 'Explore Now' button on the Home Page. By strategically placing it in a prominent and easily accessible location, we can encourage users to engage with the featured content more effectively.

I would appreciate it if you could assign the issue "Improving the Positioning of the 'Explore Now' Button in the Home Page" to me. I believe I can contribute valuable insights and implement the necessary changes to optimize the button's placement.

Looking forward to your response.

Regards,
Premsai Varma

**Comment by shramanpaul** [comment]
I would like to work on this issue under GSSOC'23.
