### ISSUE TITLE
[Gssoc'23] Add social media icons in the footer.

### ISSUE THREAD

**Issue by kanishkasah20** [NageshMandal/Engineering-Notes-Website#916]
I will add responsive social media icons in the footer.
Please assign me this issue under Gssoc'23.
Thankyou!

<img width="907" alt="image" src="https://github.com/NageshMandal/Engineering-Notes-Website/assets/114860158/ffda10f3-ab39-4a1f-b33c-801b58fd81f8">

**Comment by KmKalpana** [comment]
Hey, @kanishkasah20 could you please assign me this issue? I would like to work on it.
